/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "RCC_interface.h"
#include "GPIO_interface.h"

int main(void)
{

	GPIO_PinConfig_T LED1 =
	{
		.Port = PORTA,
		.PinNum = PIN5,
		.Mode = OUTPUT,
		.OutType = PUSH_PULL,
		.Speed = LOW,
		.PullType = NO_PULL,
	};

	RCC_u8PeripheralClkEnable(GPIOA_Per,RCC_AHB1_CLK);

	GPIO_u8PinInit(&LED1);

	GPIO_u8SetPinValue(LED1.Port, LED1.PinNum, PIN_HIGH);


//	GPIO_u8SetPinValue(Pin1.Port, Pin1.PinNum, PIN_LOW);
//
//	GPIO_u8TogglePinValue(Pin1.Port, Pin1.PinNum);

//	uint8_t val;
//	GPIO_u8ReadPinValue(Pin1.Port, Pin1.PinNum, &val);
	for(;;);
}
